{
 "title": "Solar Monitoring Realtime",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "dailycost", "label": "Daily supply cost", "query": "151.5" },
   { "name": "tariffimport", "label": "Import Tariff", "query": "30.59" },
   { "name": "tariffexport", "label": "Export Tariff", "query": "21.0" }
  ]
 },
 "panels": [
  {
   "title": "Inverter Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"data-realtime\")\r\n|>range(start: -10m, stop: now())\r\n|>filter(fn:(r) => r._field == \"I_Status\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Efficiency",
   "type": "stat",
   "description": "TODO use calculation in flux\n\nhttps://www.influxdata.com/blog/influxdb-how-to-do-joins-math-across-measurements/",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"I_efficiency_computed\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Generation",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: -10m, stop: now())\r\n|>filter(fn:(r) => r._field == \"I_AC_Power_computed\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "inverterPower = from(bucket:\"data-realtime\")\r\n|>range(start: -10m, stop: now())\r\n|>filter(fn:(r) => r._field == \"I_AC_Power_computed\")\r\n|> drop(columns:[\"_start\", \"_stop\", \"_measurement\", \"position\", \"_field\"])\r\n\r\nmeterPower = from(bucket:\"data-realtime\")\r\n|>range(start: -10m, stop: now())\r\n|>filter(fn:(r) => r._field == \"M_AC_Power_A\")\r\n|> drop(columns:[\"_start\", \"_stop\", \"_measurement\", \"position\", \"_field\"])\r\n\r\nconsumption = join(tables: {inverterPower: inverterPower, meterPower: meterPower}, on: [\"_time\"])\r\n|>map(fn: (r) => ({\r\n    r with\r\n    _value: (r._value_inverterPower - r._value_meterPower)\r\n}))\r\n|> yield(name: \"consumption_power\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"data-realtime\")\n  |> range(start: -2d )\n  |> timeShift(duration: 8h, columns: [\"_time\"])\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Solaredge_Calculated_Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Total_Energy_Consumption_kwh\")\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\n  |> last ()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"data-realtime\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> timeShift(duration: 8h, columns: [\"_time\"])\r\n  |> hourSelection(start: 5, stop: 20)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Solaredge_Calculated_Power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Total_Energy_Generation_kwh\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> last()\r\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Self Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"data-realtime\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> timeShift(duration: 8h, columns: [\"_time\"])\r\n  |> hourSelection(start: 5, stop: 20)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Solaredge_Calculated_Power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power_Self_consumption_kwh\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> last()\r\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Export",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: -10m, stop: now())\r\n|>filter(fn:(r) => r._measurement == \"sunspec_power_meter\")\r\n|>filter(fn:(r) => r._field == \"M_AC_Power_A\")\r\n|>map(fn: (r) => ({\r\n    r with\r\n    _value:\r\n      if r._value <= 0 then 0\r\n      else int(v: r._value)\r\n}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Import",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: -10m, stop: now())\r\n|>filter(fn:(r) => r._measurement == \"sunspec_power_meter\")\r\n|>filter(fn:(r) => r._field == \"M_AC_Power_A\")\r\n|>map(fn: (r) => ({\r\n    r with\r\n    _value:\r\n      if r._value >= 0 then 0\r\n      else int(v: r._value * -1.0)\r\n}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Import (kwh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"data-realtime\")\n  |> range(start: -2d)\n  |> timeShift(duration: 8h, columns: [\"_time\"])\n  |> hourSelection(start: 0, stop: 23)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Solaredge_Calculated_Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Imported_Power_kwh\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> last ()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Export (kwh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"data-realtime\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Solaredge_Calculated_Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Exported_Power_kwh\")\n  |> aggregateWindow(every: 10h, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: -10m, stop: now())\r\n|>filter(fn:(r) => r._field == \"I_Temp_Sink_computed\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"I_AC_Power_computed\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "inverterPower = from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"I_AC_Power_computed\")\r\n|> drop(columns:[\"_start\", \"_stop\", \"_measurement\", \"position\", \"_field\"])\r\n\r\nmeterPower = from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"M_AC_Power_A\")\r\n|> drop(columns:[\"_start\", \"_stop\", \"_measurement\", \"position\", \"_field\"])\r\n\r\nconsumption = join(tables: {inverterPower: inverterPower, meterPower: meterPower}, on: [\"_time\"])\r\n|>map(fn: (r) => ({\r\n    r with\r\n    _value: (r._value_inverterPower - r._value_meterPower)\r\n}))\r\n|> yield(name: \"consumption_power\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Usage (Export/Import)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._measurement == \"sunspec_power_meter\")\r\n|>filter(fn:(r) => r._field == \"M_AC_Power_A\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstairs Temperature - Central",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"displayName\"] == \"Upstairs_Central__-_Temp_and_Humidity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\" or r[\"_measurement\"] == \"temperature\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}